# Site settings
title: Rajkumar Singh
twitter_username: vigilanteRk
name: Rajkumar Singh

# Build settings
markdown: Resume

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/vigilanteRk
 - title: LinkedIn
   url: https://www.linkedin.com/in/rajkumar-singh-b3333b140/
 - title: Quora
   url: https://www.quora.com/profile/Rajkumar-Singh-70/

#Any buzzword skills you want to include
skills:
 - html/css/js
 - Bootstrap
 - MongoDb
 - NodeJs
 - ExpressJs
 - Below once are needed to be learned
 - API design 
 - Spring MVC
 - SQL
 - REST
 - Technical Architecture

#Work experience is required
roles:
 - title: Intern
   start: 2019
   end: Ongoing
   employer: Pagido
   description: Pagido startup producing a range of Digital Marketting and Web Development products. 

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   Date: 2016
   school: University of Mumbai
   
 - level: Master Of Computer Application (M.C.A)
   Date: 2019
   school: University of Mumbai
   
